site_name: appJar
site_url: http://appjar.info
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/jarvisteach/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
copyright: <p><a href='/License'>&#169; Richard Jarvis, 2015-2018</a></p>
site_description: The easiest way to build tkinter GUIs in Python.
site_author: Richard Jarvis
extra_css: [extra.css]
strict: true

markdown_extensions:
- admonition

theme:
    name: united

pages:
- Tutorials:
  - gettingStarted.md
- How-To:
  - index.md
- Reference:
  - index.md
- Explanation:
  - index.md
